### PR TITLE
Proposed improvement to contract upgradability

### PR DESCRIPTION
**Pull request by geovgy**
At its core, this is a revision to PR #110. Modified `ISmartInvoice` to only include 3 parameters: `_recipient`, `_amounts`, and `_data`. An explanation for these params:
- `_recipient`: This will always be the address that ultimately receives the funds at the end regardless of the implementation. For our current escrow implementation, this is just a relabelling of `_provider`. There could be future implementations in which the one receiving the funds is not the provider (e.i. think possibly a refund contract in which the recipient of the funds is the customer, not provider). Thus, this is a more generalized name to better fit all possible use cases.
- `_amounts`: same as it currently exists.
- `_data`: A `bytes` variable that includes an encoding of all remaining params needed dependent on implementation type. For the case of escrow, `client`, resolution data and all other params are encoded in here. For any future implementation that requires even more params, it could be possible to pass them as struct/array before encoding it in `_data` to avoid stacking too deep when decoding within the implementation's `init()` call.

The `ISmartInvoice` interface only includes `init` and serves as a base for interfaces of all implementations to inherit from. For example, `ISmartInvoiceEscrow` inherits from `ISmartInvoice`. This means our Pay Now contract can work as an implementation just by having its own interface inheriting from `ISmartInvoice` and have its completely own custom functions. Essentially, no need to conform to the same functions as the escrow implementation, and thus no restrictions for future implementations.

Mainly kept the implementation content from #110 and cleaned it up. Made it leaner. I also imported some of the relevant unit tests. All tests pass.

A few notes:
- Had to modify `rule()` in `SmartInvoiceEscrow`. For some unknown reason, grabbing an item from `RULINGS` at index `_ruling` on line 398 returned a [0,0] split regardless of what value `_ruling` is. This led to a panic code since nothing is divisible by zero. As a workaround, I created a `_getRuling()` internal function that serves the exact same purpose but actually works in returning the correct values. No clue why that works while the original way does not. We will need to investigate it but this change does not impact the result of `rule()`.
- There are a couple functions added to `SmartInvoiceEscrow.js` that I am moving to `utils.js` in the next commit.

### CODE REVIEW

**Comment by psparacino** [comment]
Ok, great. Can we actually point this PR at the branch in my repo?  It will be easier to compare against the current PR in that instance and continue to work on any other open issues before a merge to develop. these revisions look good👍 
 
There are a couple more functions (arbitrator-related) needed as well before this branch is merged; those will also be easier to integrate/track if we're working off the same branch before a merge to here.

**Comment by geovgy** [comment]
This branch is actually based off main branch so there could be merge conflicts. It was easier for me to start fresh and copy+paste your edits where needed. I'm fine making another PR to your repo so you can see the differences but I'd suggest just making a fresh branch off main as well and pull from this branch.

What updates would be needed on the arbitrator side regarding upgradability?

**Comment by psparacino** [comment]
ok, i think it's going to be easier if we work off of one 'upgrade' branch. I pulled this branch from your repo and merged with the current open PR branch. I'll push to the open PR, #110, after I get a chance to address a couple items and then it should be clean w/ the current revisions, w/o any conflicts and with a commit history, which we can work off of going forward. that work?

Leaving this up for the moment, but will close after I push the merged branch.

**Comment by geovgy** [comment]
I would hold off on closing this branch until the updates you made on #110 are reviewed. My preference is to instead continue with this PR moving forward since it includes the core implementation and access control components from your branch and already refined for merge to `develop` branch. That was the intention behind making this PR. Making the other PR to `feat/contract-upgrades` on your repo was just to clearly show the differences.

Still unsure what arbitration-related functions you mentioned need to be added except possibly changing resolutionRates to a double mapping structure like `implementations` so rates are based on address AND invoice type. Another thing I believe may need to be done is either one of the following: (1) add factory address as one of the decoded params out of `_data` in the SmartInvoiceEscrow contract. The address is needed to fetch the resolution rate from factory via external call. This address is currently just `msg.sender` and reverts if init is called by a non-contract account. Assumption is that only only factory is executing `init()`. Or, (2) we make an interface ID for SmartInvoiceFactory (similar to ERCs) and check for it on `init()` in the escrow contract. If returns false, then `init()` is reverted.

Other pending items:
- Update subgraph to match event changes + additions
- A few more unit tests focused on implementation management
- Update dapp to handle param changes

**Comment by psparacino** [comment]
closing as all revisions have been merged into 110

**Pull request closed without merging**
